# Generated by Django 4.1.1 on 2022-09-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='blogs', to='blog.tag', verbose_name='تگ ها'),
        ),
    ]
